#这是插件的配置文件，所有的设置都在这里
Settings:

  #这个选项可以完全禁用或启用经验修补，当设置为true时，经验修补可以使用，当设置为false时，经验修补没有作用
  Mend: true

  #这个选项是经验修补减弱的开关，开启后经验修补消耗的经验将增加
  Slow_Mend: true

  #这个选项是经验修补的减弱系数，将决定经验修补消耗的经验量。数字越大消耗越多，换算大约为“1/[最大值]”
  #如果你够狠，你可以让你的玩家挂几个小时的经验农场都修不好一把镐子（
  Mitigation_Coefficient: 5

  #这是一个黑名单可以指定禁用的物品，此列表内的物品会被禁止进行修补
  Ban_Item:
  #- DIAMOND_AXE

  #这是一个白名单可以指定禁用的物品,此列表内的物品将不受任何限制 注：如果于黑名单同时填写，将优先白名单
  Allow_Item:
  #- DIAMOND_AXE


  #这是一个限制经验修补次数的功能
  Max_Mend_Limit:

    #是否启用，如果启用将限制经验修补的修补次数，如果到达次数物品将不会被修补
    Enable: true

    #这个是最大修补次数，注：这个是修补次数，玩家吸收经验就会增加，而不是触发修补
    Max_Number: 500

    #在修补次数耗尽后，是否给玩家发送信息
    Deactivate_Message: true

    #↑发送的信息内容
    Message: 你的这件装备已经很破旧了，是时候换一个了。

    #装备达到上限后是否更改名称
    Change_Item_Name: true

    #更改名字前缀的内容
    Item_Prefix: §7破损的-

    #这是限制提示字体的颜色，请输入单个字母或数字，超出的部分会被截取（别作，万一没截取全服经验修补都嘚炸）
    Color: 9



