name: slow_mending
version: '1.1.8'
main: org.sbbpl.slow_mending.Slow_mending
api-version: '1.20'
description: A plugin that mack mend slower and expensive than before.
permissions:
  slowmending.command:
    default: op
commands:
  slowmending:
    description: A plugin that mack mend slower and expensive than before.
    usage: /slowmending <set|reload|version|help>
    aliases: slmend
    permission: slowmending.command

