name: slow_mending
version: 'v1.2'
main: org.sbbpl.slow_mending.Slow_mending
api-version: '1.20'
commands:
  slowmending:
    description: A plugin that mack mend slower and expensive than before.
    aliases: slmend
    permission: slowmwnding.use

